
//Array Unidimensional 
let listalunos = ['Roger: ', 'Denis: ', 'Paulo: ', 'Daniel:', 'Igor:  '];
//console.log(`Array Unidimensional : ${listalunos}`);

//Array bidimensional
const perfil = [
[ '10', '     2000' ,'   Turma B'],
[ '8'  ,  '      2001', '   Turma C'],
[ '7.5', '    2002', '   Turma D'],
[ '5.5', '    2000', '   Turma G'],
[ '9.8', '    2003', '   Turma A'],

];
//console.log(`Array Bidimensional : ${perfil}`)

console.log('Aluno:  Nota: Nascimento:  Turma:');
console.log(` ${listalunos[0]} ${perfil[0]}`);
console.log(` ${listalunos[1]} ${perfil[1]}`);
console.log(` ${listalunos[2]} ${perfil[2]}`);
console.log(` ${listalunos[3]} ${perfil[3]}`);
console.log(` ${listalunos[4]} ${perfil[4]}`);

